version: '3.8'
services:
  app:
    build: .
    container_name: node_app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - MERCHANT_POS_ID=${MERCHANT_POS_ID}
      - KEY=${KEY}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/usr/src/app/swagger.yml
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
